### ISSUE TITLE
PR creation "manually" merges PRs with failing status

### ISSUE THREAD

**Issue by bittrance** [XenitAB/gitops-promotion#137]
If a GitHub repo has auto-merge off, `CreatePR` will merge it immediately. At the time of merging, there are no status checks, so we cannot know whether it is ok to merge it - we just do it anyway. I think this is a problematic default behavior. I can see two different options:
  1. refuse to merge PRs manually, generating a clear error message ("Your repository does not allow auto-merge. Please merge the PR manually.") and thus failing the new/promote workflow.
  1. as 1. but enable configuration in `gitops-promotion.yaml` to allow "immediate" merge.

**Comment by bittrance** [comment]
It can be noted that the status command currently requests a PR for the triggering branch, filtering to only open PRs. It will thus fail if the PR is already merged.

**Comment by simongottschlag** [comment]
I like the second option. `automerge: true | false | immediate`

If not `immediate`, never use the current behavior.

Needs to be checked with Azure DevOps to make sure we don't break any expected behavior over there.

**Comment by bittrance** [comment]
PR #145 removed the manual merge and introduced a check that we fail if GitHub auto-merge is not available.
