### ISSUE TITLE
Status command times out on commits that Flux has skipped

### ISSUE THREAD

**Issue by bittrance** [XenitAB/gitops-promotion#175]
If a new commit arrives on the merge target branch (e.g. main) shortly after `status` starts, Flux may not have started reconciliation of the commit known to `status` and will thus never mark that commit as reconciled, resulting in a timeout for `status`. Also, a developer may react to a failed reconciliation notification with a quick commit to the merge target branch while promotion is in progress, thus providing a fix to the failed reconciliation, but `status` will still be looking at the failed reconciliation of the merge commit for the preceding environment. Reasonably, such a fix should unblock the promotion flow.

**Comment by simongottschlag** [comment]
I think we had the same with v1 and always looked at the latest commit in the directory: https://github.com/XenitAB/azure-devops-templates/blob/4fe5da9521ee69cac3db028223b5c1d1fdc81322/gitops/deploy/deploy.yaml#L173

**Comment by bittrance** [comment]
Indeed, as @simongottschlag says, we should be looking at the most recent commit for the env dir. Technically speaking, we should look at the same thing as https://github.com/XenitAB/gitops-promotion/blob/0800017382efa9624eb7ef6ca2af152fd24cbc24/pkg/command/promote.go#L51 .

**Comment by bittrance** [comment]
On further meditation, since Flux will always try to reconcile the most recent commit on the source branch, it can always happen that any path-based strategy (or limiting rule whatever) can keep us from finding the commit that actually contains a Flux status. In the end, I decided to just look at head on main.
