### ISSUE TITLE
Skip status check on manual PR

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/gitops-promotion#46]
`StatusCommand()` fails when doing manual PR to the GitOps repo, causing build validation in Azure DevOps to fail.

The following error occurs:

```
ERROR: failed getting pr for current branch: invalid metadata: "<PR Description>"
```

We should most likely add a check early to see if this is a GitOps promotion PR or not and allow it through.

My suggestion is to either put all PRs from GitOps promotion to a specific path - like `gitops-promotion/<old-path>` or add something like a tag in the description or title, like `[gitops-promotion] <old title>` and check for these before continuing.

@NissesSenap @phillebaba what would you prefer?

**Comment by NissesSenap** [comment]
Then I would prefer `gitops-promotion/<old-path>`
The good thing there is that you can use filepath logick to easily split things up from a implementation point of view. 

And from a user point of view I don't think it really matters with `gitops-promotion/<old-path>` vs `[gitops-promotion] <old title>`

**Comment by phillebaba** [comment]
I would suggest we solve this by adding a prefix to all branches. Even if PR tags is nicer it would be difficult to implement if a provider does not have that feature. So the solution would be "gitops-promotion/*".
