### ISSUE TITLE
Integration tests should test the final artifact

### ISSUE THREAD

**Issue by bittrance** [XenitAB/gitops-promotion#92]
The end-to-end tests currently performs its tests by invoking the various command functions (i.e. the various pkg/command/* files). This means that it does not test either the actual cli invocations or the built container. I think it would be nice if these tests invoked `docker run gitops-promotion:latest <command> <options>` instead so that we test the actual artifact before pushing. This would ensure there are no major screwups in the build process. Opinions @simongottschlag @NissesSenap ?

**Comment by NissesSenap** [comment]
I agree as long as it's a resonable amount of work.
